### ISSUE TITLE
La carpeta prioridad no debe estar dentro de navigation

### ISSUE THREAD

**Issue by AlexanderST01** [Robelin09/PrioridadRegistro#6]
https://github.com/Robelin09/PrioridadRegistro/blob/c33ba9e09d3dc8e7031f2e65ac9c8e769f818cd2/app/src/main/java/edu/ucne/prioridadregistro/presentation/navigation/PrioridadNavHost.kt#L35

**Comment by Robelin09** [comment]
Solucionado
