### ISSUE TITLE
No deberias de poner la validación para dias compromiso y descripción de forma anidada

### ISSUE THREAD

**Issue by AlexanderST01** [Robelin09/PrioridadRegistro#7]
https://github.com/Robelin09/PrioridadRegistro/blob/c33ba9e09d3dc8e7031f2e65ac9c8e769f818cd2/app/src/main/java/edu/ucne/prioridadregistro/presentation/navigation/prioridad/PrioridadScreen.kt#L71

**Comment by Robelin09** [comment]
Completado
